# Site settings
title: New York To Mumbai By Road
email: kgmodi@gmail.com
description: > # 
  Three people will embark on a journey starting in New York crossing continents and driving thousands of miles from London to Mumbai for charity and adventure.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nytomumbai.org" # the base hostname & protocol for your site
#url: "http://localhost"
port: "80"
#port: "4444"
# Build settings
markdown: kramdown

# Team names, titles and social links
people:
- name: Kunal Modi
  pic: images/kunal-profile-color.png
  position: Software Development Manager, New Jersey
  social:
    - title: facebook
      url: http://www.facebook.com/kgmodi
    - title: twitter
      url: http://www.twitter.com/kgmodi
    - title: linkedin
      url: http://www.linkedin.com/in/kunalmodi
  bio: Kunal likes to explore and finds crossing land borders fascinating. He was raised in Mumbai, India and currently lives and works in New Jersey. He was a part of <a href="http://lastresponders.org/timbuktuchallenge2012.html" target="_blank">Team Last Responders</a> on the Timbuktu Challenge 2012 where he drove an ambulance from the London to Mali. Since then Kunal always wanted to travel back to his native land by road. The cause of education is very dear to him. He can be described as the one who reads maps but loves to get lost on the road before he finds the right route.

- name: Devanshi Modi
  pic: images/devanshi-profile-color.png
  position: Physical Therapist, New Jersey 
  social:
    - title: facebook
      url: http://www.facebook.com/devanshi.gandhi.37
    - title: linkedin
      url: http://www.linkedin.com/in/devanshi-modi-930bb3b1
  bio: Devanshi is a motivated learner, the one ready to face unforeseen challenges. Loves talking and interacting with different people. Natural beauty enchants her. She is raised in Mumbai, India and currently lives in New Jersey. She can be described as being free spirited, excited as well as anxious to drive on unknown narrow roads and to parallel park.

support-team:
- name: Vrunda Modi
  pic: images/vrunda-profile.jpg
  position:
  social:
    - title: facebook
      url: http://www.facebook.com/vrunmodi
    - title: linkedin
      url: https://www.linkedin.com/in/vrunda-modi-78924a23
  bio:
   
- name: Shrida Shah Pradhan 
  pic: images/shrida-profile-color.png
  position:
  # social:
  #     - title: facebook
  #       url: http://www.facebook.com/shirishiri.shahpradhan
  #     - title: linkedin
  #       url: http://www.linkedin.com/in/shrida-shahpradhan-81270811
  bio:
  
charities:
- name: Kedi Residential School for Tribal Girls
  url: http://www.kedischool.org/
  location: Tithal, Valsad, India
  # logo-url: images/logo01.jpg
  logo-url: images/kedi-school-logo.png
  paypalId: JX5PUPM9CUUSA
  description: Kedi Residential High School has the most unique educational curriculum among other residential schools of its kind in this rural part of the district. Commitment to the challenging program is vital from students, teachers and parents. Education, boarding, meal, clothing, and medical care to more than 100 girls of economically deprived tribal areas are free-of-charge. Every student at Kedi arrives here by choice. Kedi school is now coming up with a new project to provide Scholarship program after 12th for higher education. In this project, the school will offer part payment of fees and scholarships to those who want to continue higher studies. We aim to raise $5000 for the same. Download the <a href="assets/kedi-school.pdf">Kedi School Brochure</a>
  images: 
    - url: images/experimental-learning.jpg
    - url: images/fun-with-learning.jpg
    - url: images/interactive-teaching.jpg

main-sections:
- name: Route
  logo: globe
  description: Flying from New York to London and then driving to Mumbai, we will be passing through 15 countries along the Silk Route.
  button-name: Planned Route
  url: route.html
- name: Vehicle
  logo: car
  description: This car is going to be the integral part of our journey. We are making efforts to select a vehicle which will serve as our home on the journey.
  button-name: More About Vehicle Soon
  # url:
- name: Charities
  logo: child
  description: We will be raising awareness and funds for Kedi Residential School For Tribal Girls in India.<br/><br/>
  button-name: More About the Kedi School
  url: charities.html

route: 
- city: New York
  country: USA
- city: London
  country: UK
- city: Paris
  country: France
- city: Lyon
  country: France
- city: Geneva
  country: Switzerland
- city: Lichtenstein
  country: Germany
- city: Hanover
  country: Germany
- city: Berlin
  country: Germany
- city: Poznań 
  country: Poland
- city: Warsaw
  country: Poland
- city: Vilnius
  country: Lithuania
- city: Riga
  country: Latvia
- city: Tallinn
  country: Estonia
- city: St Petersburg
  country: Russia
- city: Moscow
  country: Russia
- city: 
  country: Kazakhstan
- city: Sary-Tash
  country: Kyrgyzstan
- city: Kashgar
  country: China
- city: Hotan, Xinjiang
  country: China
- city: Minfeng County, Hotan
  country: China
- city: Qarqan, Bayingol
  country: China
- city: Huatugouzhen, Haixi
  country: China
- city: Golmud
  country: China
- city: Tongren, Huangnan
  country: China
- city: Xiahe, Gannan
  country: China
- city: Ruoergai Xian
  country: China
- city: Miyaluozhen
  country: China
- city: Panzhihua
  country: China
- city: Dali
  country: China
- city: Ruili
  country: China
- city: Muse, Shan
  country: Myanmar (Burma)
- city: Mandalay
  country: Myanmar (Burma) 
- city: Tamu, Sagaing Region
  country: Myanmar (Burma)  
- city: Moreh, Manipur
  country: India  
- city: Imphal, Manipur
  country: India  
- city: Dispur, Guwahati, Assam
  country: India  
- city: Darjeeling
  country: India  
- city: Agra
  country: India  
- city: Vadodara
  country: India  
- city: Mumbai, Maharashtra
  country: India  

