# Site settings
title: New York To Mumbai By Road
email: kgmodi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/nyctomumbai2/" # the subpath of your site, e.g. /blog/
# url: "http://kgmodi.github.io/nyctomumbai2" # the base hostname & protocol for your site
url: "http://locahost"
twitter_username: jekyllrb
github_username:  jekyll
port: "4444"
# Build settings
markdown: kramdown
