# Site settings
title: New York To Mumbai By Road
email: kgmodi@gmail.com
description: > # 
  Three people will embark on a journey starting in New York crossing continents and driving thousands of miles from London to Mumbai for charity and adventure.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nytomumbai.org" # the base hostname & protocol for your site
# url: "http://localhost"
twitter_username: kgmodi
github_username:  kgmodi
port: "80"
# port: "4444"
# Build settings
markdown: kramdown

# Team names, titles and social links
people:
- name: Kunal Modi
  pic: images/kunal-profile.jpg
  position:
  social:
    - title: facebook
      url: http://www.facebook.com/kgmodi
    - title: linkedin
      url: http://www.linkedin.com/in/kunalmodi

- name: Devanshi Modi
  pic: images/devanshi-profile.jpg
  position: 
  social:
    - title: facebook
      url: http://www.facebook.com/devanshi.gandhi.37
    - title: linkedin
      url: http://www.linkedin.com/in/devanshi-modi-930bb3b1

- name: Shrida Shah Pradhan 
  pic: images/shrida-profile.jpg
  position: 
  social:
      - title: facebook
        url: http://www.facebook.com/shirishiri.shahpradhan
      - title: linkedin
        url: http://www.linkedin.com/in/shrida-shahpradhan-81270811

support-team:
- name: Vrunda Modi
  pic: images/vrunda-profile.jpg
  position:
  social:
    - title: facebook
      url: http://www.facebook.com/vrunmodi
    - title: linkedin
      url: https://www.linkedin.com/in/vrunda-modi-78924a23

charities:
- name: Skanda Vale Hospice
  url: http://www.skandavalehospice.org/
  location: Wales, UK
  logo-url: images/skanda-vale-hospice-web-logo1.png
  paypalId: JX5PUPM9CUUSA
  description: At Skandavale hospice, the aim is to improve the lives of people who have a life-limiting or terminal illness, helping them to live well before they die. They not only take care of people’s physical needs, but look after their practical, physical, emotional, social and spiritual needs as well. They support careers, family members and close friends, both during a person’s illness and during bereavement. They believe that great palliative care is about getting the details right, so that a person can be cared for in an attentive, loving and dignified way. They have the enthusiasm, the time and the resources to be able to offer a high standard of care, personally tailored to suit the specific needs of the individual. We plan to raise funds to support their efforts.

- name: Kedi Residential School for Tribal Girls
  url: http://www.kedischool.org/
  location: Tithal, Valsad, India
  logo-url: images/logo01.jpg
  paypalId: X2RDCSVGGFE38
  description: Kedi Residential High School has the most unique educational curriculum among other residential schools of its kind in this rural part of the district. Commitment to the challenging program is vital from students, teachers and parents. Education, boarding, meal, clothing, and medical care to more than 100 girls of economically deprived tribal areas are free-of-charge. Every student at Kedi arrives here by choice. Kedi school is now coming up with a new project to provide Scholarship program after 12th for higher education. In this project, the school will offer part payment of fees and scholarships to those who want to continue higher studies. We aim to donate and raise funds for the same.


main-sections:
- name: Route
  logo: globe
  description: Flying from New York to London and then driving to Mumbai, we will be passing through 17 countries along the Silk Route.
  button-name: Planned Route
  url: route.html
- name: Vehicle
  logo: car
  description: This car is going to be the integral part of our journey. We are making efforts to select a vehicle which will serve as our home on the journey.
  button-name: More About Vehicle
  url: 
- name: Charities
  logo: child
  description: We will be raising awareness and funds for two Charities - Skanda Vale Hospice in UK and Kedi School in India.
  button-name: More About Charities
  url: charities.html

route: 
- city: New York
  country: USA
- city: London
  country: UK
- city: Paris
  country: France
- city: Lyon
  country: France
- city: Geneva
  country: Switzerland
- city: Lichtenstein
  country: Germany
- city: Hanover
  country: Germany
- city: Berlin
  country: Germany
- city: Poznań 
  country: Poland
- city: Warsaw
  country: Poland
- city: Vilnius
  country: Lithuania
- city: Riga
  country: Latvia
- city: Tallinn
  country: Estonia
- city: St Petersburg
  country: Russia
- city: Moscow
  country: Russia
- city: 
  country: Kazakhstan
- city: Sary-Tash
  country: Kyrgyzstan
- city: Kashgar
  country: China
- city: Hotan, Xinjiang
  country: China
- city: Minfeng County, Hotan
  country: China
- city: Qarqan, Bayingol
  country: China
- city: Huatugouzhen, Haixi
  country: China
- city: Golmud
  country: China
- city: Tongren, Huangnan
  country: China
- city: Xiahe, Gannan
  country: China
- city: Ruoergai Xian
  country: China
- city: Miyaluozhen
  country: China
- city: Panzhihua
  country: China
- city: Dali
  country: China
- city: Ruili
  country: China
- city: Muse, Shan
  country: Myanmar (Burma)
- city: Mandalay
  country: Myanmar (Burma) 
- city: Tamu, Sagaing Region
  country: Myanmar (Burma)  
- city: Moreh, Manipur
  country: India  
- city: Imphal, Manipur
  country: India  
- city: Dispur, Guwahati, Assam
  country: India  
- city: Darjeeling
  country: India  
- city: Agra
  country: India  
- city: Vadodara
  country: India  
- city: Mumbai, Maharashtra
  country: India  

